### ISSUE TITLE
call 'shell' like 'sh' of python

### ISSUE THREAD

**Issue by Freakwill** [GUI/lua-shell-games#1]
Can we implement
`shell.run({ "touch", "/tmp/hello.txt" })`
as `shell.touch("/tmp/hello.txt")` in the way as 'sh' of python. 'sh' is lua-shell-games of python

I found luash has such function.

**Comment by GUI** [comment]
@Freakwill: Thanks for the suggestion. However, I think I'd prefer to keep the API of this module more consistent (even if it means it's a tad more verbose), rather than having "magic" methods that might make the API more ambiguous (eg, if I wanted to execute a command named `run`, that becomes trickier with the proposed API, since we already have a lua function `shell.run`).

I hope that makes sense, but let me know if you have any further feedback or suggestions. Thanks!
